"""add contact_id to jobs

Revision ID: 39f954d09918
Revises: d75e2d182aa6
Create Date: 2026-05-29 07:41:28.010985

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '39f954d09918'
down_revision: Union[str, None] = 'd75e2d182aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
