"""add pickup delivery km

Revision ID: 507d4ea558bb
Revises: 5a095ec057ff
Create Date: 2026-05-27 06:03:44.202823

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '507d4ea558bb'
down_revision: Union[str, None] = '5a095ec057ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('pickup_km', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('delivery_km', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'delivery_km')
    op.drop_column('jobs', 'pickup_km')
    # ### end Alembic commands ###
