"""add job_id to invoices

Revision ID: 5332f0f97c46
Revises: 39f954d09918
Create Date: 2026-05-29 09:12:24.162049

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5332f0f97c46'
down_revision: Union[str, None] = '39f954d09918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
