"""add assigned_to_id to jobs

Revision ID: 5a095ec057ff
Revises: d1d4a82a63d0
Create Date: 2026-05-22 09:14:30.267974

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5a095ec057ff'
down_revision: Union[str, None] = 'd1d4a82a63d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'assigned_to_id')
    # ### end Alembic commands ###
