"""add pickup and delivery status

Revision ID: 86e25e3303f6
Revises: 507d4ea558bb
Create Date: 2026-05-27 06:23:16.551641

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '86e25e3303f6'
down_revision: Union[str, None] = '507d4ea558bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
