"""add picked_up delivered to job_status_enum

Revision ID: a3e50d93997e
Revises: 86e25e3303f6
Create Date: 2026-05-27 14:21:02.472827

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a3e50d93997e'
down_revision: Union[str, None] = '86e25e3303f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
