"""add assigned_to_id to jobs

Revision ID: d1d4a82a63d0
Revises: 
Create Date: 2026-05-22 09:02:32.675349

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd1d4a82a63d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
