"""add contact_id to jobs

Revision ID: d75e2d182aa6
Revises: a3e50d93997e
Create Date: 2026-05-29 07:29:31.027743

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd75e2d182aa6'
down_revision: Union[str, None] = 'a3e50d93997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'customer_contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'contact_id')
    # ### end Alembic commands ###
